default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: passwordtest
  host: localhost
  pool: 5

development:
  <<: *default
  database: pokedex_development

test:
  <<: *default
  database: pokedex_test

production:
  <<: *default
  database: pokedex_production
  username: pokedex
  password: <%= ENV['POKEDEX_DATABASE_PASSWORD'] %>
